### ISSUE TITLE
Corrupted wallet file

### ISSUE THREAD

**Issue by appkoders** [blockchain-next/TycheCash#1]
I just created a wallet and now I cannot open it anymore. Its saying `Error: failed to load wallet: can't load wallet file 'pool.wallet', check password.`   

I know the password is correct. Comparing the size of other wallets I created looks like the wallet got corrupted after simplewallet did not close properly. Its size is now just 725 bytes compared to the normal 161800 byte size of a newly created wallet.  Is there any way to recover the wallet?

The problem with this wallet is it doesnt give you any way to display your private spend key or import new wallets. The wallet should be updated to use the updated simplewallet with more options.

**Comment by blockchain-next** [comment]
U can now import wallet in Windows /Linux GUI . That should solve ur problem.

**Comment by appkoders** [comment]
Finally Thanks.
